export const product = [
  { title: "Tshirt", id: 0 },
  { title: "Jeans", id: 1 },
  { title: "Jacet", id: 2 },
  { title: "Shirt", id: 3 },
  { title: "Lower", id: 4 },
  { title: "Hoodie", id: 5 },
]

export const tshirt = [
  { brand: "LV", color: "Black", price: "100", code: "t1", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t2", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t3", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t4", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t5", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t6", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t7", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t8", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t9", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t9", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t11", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
  { brand: "LV", color: "Black", price: "100", code: "t12", url: require("../Images/tshirt.webp"), decription: 'A product description is the marketing copy that explains what a product is and why its worth purchasing.' },
]

export const jeans = [
  { brand: "Denim", color: "green", price: "1200", code: "j1" },
  { brand: "Denim", color: "green", price: "1200", code: "j2" },
  { brand: "Denim", color: "green", price: "1200", code: "j3" },
  { brand: "Denim", color: "green", price: "1200", code: "j4" },
  { brand: "Denim", color: "green", price: "1200", code: "j5" },
  { brand: "Denim", color: "green", price: "1200", code: "j6" },
  { brand: "Denim", color: "green", price: "1200", code: "j7" },
  { brand: "Denim", color: "green", price: "1200", code: "j8" },
  { brand: "Denim", color: "green", price: "1200", code: "j9" },
  { brand: "Denim", color: "green", price: "1200", code: "j10" },
  { brand: "Denim", color: "green", price: "1200", code: "j11" },
]
export const jacket = [
  { brand: "Gucci", color: "red", price: "1000", code: "jk1" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk2" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk3" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk4" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk5" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk6" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk7" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk8" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk9" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk10" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk11" },
  { brand: "Gucci", color: "red", price: "1000", code: "jk12" },
]
export const shirt = [
  { brand: "Gucci", color: "yellow", price: "3000", code: "s1" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s2" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s3" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s4" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s5" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s6" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s7" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s8" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s9" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s10" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s11" },
  { brand: "Gucci", color: "yellow", price: "3000", code: "s12" },
]
export const lower = [
  { brand: "nike", color: "brown", price: "1000", code: "l1" },
  { brand: "nike", color: "brown", price: "1000", code: "l2" },
  { brand: "nike", color: "brown", price: "1000", code: "l3" },
  { brand: "nike", color: "brown", price: "1000", code: "l4" },
  { brand: "nike", color: "brown", price: "1000", code: "l5" },
  { brand: "nike", color: "brown", price: "1000", code: "l6" },
  { brand: "nike", color: "brown", price: "1000", code: "l7" },
  { brand: "nike", color: "brown", price: "1000", code: "l8" },
  { brand: "nike", color: "brown", price: "1000", code: "l9" },
  { brand: "nike", color: "brown", price: "1000", code: "l10" },
  { brand: "nike", color: "brown", price: "1000", code: "l1" },
  { brand: "nike", color: "brown", price: "1000", code: "l2" },
]
export const hoodie = [
  { brand: "Gucci", color: "red", price: "4000", code: "h1" },
  { brand: "Gucci", color: "red", price: "4000", code: "h2" },
  { brand: "Gucci", color: "red", price: "4000", code: "h3" },
  { brand: "Gucci", color: "red", price: "4000", code: "h4" },
  { brand: "Gucci", color: "red", price: "4000", code: "h5" },
  { brand: "Gucci", color: "red", price: "4000", code: "h6" },
  { brand: "Gucci", color: "red", price: "4000", code: "h7" },
  { brand: "Gucci", color: "red", price: "4000", code: "h8" },
  { brand: "Gucci", color: "red", price: "4000", code: "h9" },
  { brand: "Gucci", color: "red", price: "4000", code: "h10" },
  { brand: "Gucci", color: "red", price: "4000", code: "h11" },
  { brand: "Gucci", color: "red", price: "4000", code: "h12" },
]