export const product=[
    {title:"Tshirt",id:0},
    {title:"Jeans",id:1},
    {title:"Jacet",id:2},
    {title:"Shirt",id:3},
    {title:"Lower",id:4},
    {title:"Hoodie",id:5},
  ]
  
  const tshirt=[
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
    {brand:"LV",color:"Black",price:"100"},
  ]
  
  const jeans=[
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
    {brand:"Denim",color:"Black",price:"1200"},
  ]
  const jacket=[
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
  ]
  const shirt=[
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
  ]
  const lower=[
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
  ]
  const hoodie=[
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
    {brand:"Gucci",color:"red",price:"1000"},
  ]